# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ricardo "Unreal" Sousa
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "//localhost:4000" # the base hostname & protocol for your site

# Site-wide content settings
contact: # displayed in header
    mail:
        text: example@example.com
        icon: envelope # see https://fortawesome.github.io/Font-Awesome/icons/
        url: mailto:example@example.com
    facebook:
        text: /example
        icon: facebook-square
        url: https://example.com
    steam:
        text: /id/example
        icon: steam-square
        url: https://example.com

# Build settings
markdown: kramdown
